[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Diff: https://www.diffchecker.com/XpsJPeq8/

# Works: manual remapping
remappings = [
    # Same
    "create2-helpers/=lib/seadrop/lib/create2-helpers/",
    "create2-scripts/=lib/seadrop/lib/create2-helpers/script/",
    "ds-test/=lib/seadrop/lib/ds-test/src/",
    "ERC721A-Upgradeable/=lib/seadrop/lib/ERC721A-Upgradeable/contracts/",
    "ERC721A/=lib/seadrop/lib/ERC721A/contracts/",
    "forge-std/=lib/forge-std/src/",
    "murky/=lib/seadrop/lib/murky/src/",
    "operator-filter-registry/=lib/seadrop/lib/operator-filter-registry/src/",
    "seadrop/=lib/seadrop/",
    "solmate/=lib/seadrop/lib/solmate/src/",

    # Different
    "openzeppelin-contracts-upgradeable/=lib/seadrop/lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin-contracts/=lib/seadrop/lib/openzeppelin-contracts/contracts/",
    "openzeppelin/=lib/seadrop/lib/openzeppelin-contracts/contracts/",
    "utility-contracts/=lib/seadrop/lib/utility-contracts/src/",
]

# Does not work: automatic remapping
# remappings = [
#     # Same
#     "create2-helpers/=lib/seadrop/lib/create2-helpers/",
#     "create2-scripts/=lib/seadrop/lib/create2-helpers/script/",
#     "ds-test/=lib/seadrop/lib/ds-test/src/",
#     "ERC721A-Upgradeable/=lib/seadrop/lib/ERC721A-Upgradeable/contracts/",
#     "ERC721A/=lib/seadrop/lib/ERC721A/contracts/",
#     "forge-std/=lib/forge-std/src/",
#     "murky/=lib/seadrop/lib/murky/src/",
#     "operator-filter-registry/=lib/seadrop/lib/operator-filter-registry/src/",
#     "seadrop/=lib/seadrop/",
#     "solmate/=lib/seadrop/lib/solmate/src/",

#     # Different
#     "openzeppelin-contracts-upgradeable/=lib/seadrop/lib/openzeppelin-contracts-upgradeable/",
#     "openzeppelin-contracts/=lib/seadrop/lib/openzeppelin-contracts/",
#     "utility-contracts/=lib/seadrop/lib/utility-contracts/",
# ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
